### ISSUE TITLE
Resize is not defined

### ISSUE THREAD

**Issue by enricodeleo** [flatanimals/vue-media-queries#2]
After installing and configuring the plugin I get this error:

```log
vue.runtime.esm.js:1737 TypeError: Cannot read property 'resize' of undefined
    at VueComponent.get (vue-media-queries.mjs:724)
    at VueComponent.isTablet (vue-media-queries.mjs:461)
    at Watcher.get (vue.runtime.esm.js:3138)
    at Watcher.evaluate (vue.runtime.esm.js:3245)
    at VueComponent.computedGetter [as isTablet] (vue.runtime.esm.js:3503)
    at Object.get (vue.runtime.esm.js:1916)
    at Proxy.render (Main.vue:240)
    at VueComponent.Vue._render (vue.runtime.esm.js:4540)
    at VueComponent.updateComponent (vue.runtime.esm.js:2784)
    at Watcher.get (vue.runtime.esm.js:3138)
```

I tried both **with and without** the `Bulma` mixin but nothing changes, it's like it doesn't find `this`.

This is what I see within Vue Devtools when the Bulma mixin is on:

![image](https://user-images.githubusercontent.com/3534555/43234372-ef4636ca-907b-11e8-8de1-0d8e3d2b56a6.png)

Can you please help me figuring out how to make this plugin work?

**Comment by flatanimals** [comment]
I'l do the best I can to help you. Could you provide me a sample of your usage and an overview of your environment so I can attempt to replicate this issue?

**Comment by enricodeleo** [comment]
Thank you! Luckily for me already have a repository because I'm working on this starter kit I made for future works on vue+parceljs https://github.com/enricodeleo/vue-parceljs-starter 

I'm currently using `vue-mq` with 

```js
Vue.mixin({
  computed: {
    isMobile() {
      return ['sm', 'md', 'lg', 'xl'].indexOf(this.$mq) >= 0;
    },
    isMobileOnly() {
      return ['sm'].indexOf(this.$mq) >= 0;
    },
    isTablet() {
      return ['md', 'lg', 'xl'].indexOf(this.$mq) >= 0;
    },
    isTabletOnly() {
      return ['md'].indexOf(this.$mq) >= 0;
    },
    isTouch() {
      return ['sm', 'md'].indexOf(this.$mq) >= 0;
    },
    isDesktop() {
      return ['lg', 'xl'].indexOf(this.$mq) >= 0;
    },
    isDesktopOnly() {
      return ['lg'].indexOf(this.$mq) >= 0;
    },
    isWideScreen() {
      return ['xl'].indexOf(this.$mq) >= 0;
    },
  },
});

```

In order to himitate the same behaviour of your mixin with bulma and it works like a charm. That's because I think the problem is not on media queries itself (if it was, even this other plugin should not work).
